title: Ben Harvey
tagline: WordPress Consultant - Somerset
email: ben@benharveywp.com
location:
  county: Somerset
description: >
  Strategic advice and practical training for WordPress sites.
  I help you make informed decisions and use your platform effectively.
url: "https://benharveywp.com"
baseurl: ""