title: Ben Harvey
tagline: Freelance WordPress Developer - Somerset
email: ben@benharveywp.com
location:
  county: Somerset
description: >
  Strategic advice, practical training and custom development for WordPress sites.
  I help you make informed decisions and use your platform effectively.
url: "https://benharveywp.com"
baseurl: ""